swagger: '2.0'
info:
  description: 'A sample object containing standard properties'
  title: 'Sample: flat object'

definitions:

  FlatObjectWithNumberOptions:
    type: object
    description: Specifies a geographic location in terms of its Latitude and Longitude
    required:
      - latitude
    properties:
      latitude:
        type: number
        format: double
        description: 'The latitude in degrees. It must be in the range [-90.0, +90.0]'
        minimum: -90
        maximum: 90
      description:
        type: string
        minLength: 1
        maxLength: 10
