swagger: '2.0'
info:
  description: 'A sample object containing standard properties'
  title: 'Sample: flat object'

definitions:

  FlatObject:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        enum: ["a", "b", "c"]
