openapi: 3.0.1
info:
  description: 'An object with string to string mapping in a refed object'
  title: 'Sample: mapping in a referenced object 1'
  version: 1.3.8

components:
  schemas:

    RefObject:
      type: object
      properties:
        object_with_map:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MapStringToString'

    MapStringToString:
      type: object
      additionalProperties:
        type: string
