swagger: '2.0'
info:
  description: 'An object with string to string mapping'
  title: 'Sample: with map'
  version: 1.2.9

definitions:

  MapStringToString:
    type: object
    additionalProperties:
      type: string
